substitutions:
  deviceString: Hydra

esphome:
  name: hydra

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encription

ota:
  password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.134
    gateway: 192.168.0.1
    subnet: 255.255.255.0

captive_portal:

light:
  - platform: monochromatic
    name: "LED Lights 1"
    output: output_component1

  - platform: monochromatic
    name: "LED Lights 2"
    output: output_component2

  - platform: monochromatic
    name: "LED Lights 3"
    output: output_component3

  - platform: monochromatic
    name: "LED Lights 4"
    output: output_component4
  
output:
  - platform: ledc
    id: output_component1
    pin: GPIO14

  - platform: ledc
    id: output_component2
    pin: GPIO27

  - platform: ledc
    id: output_component3
    pin: GPIO26

  - platform: ledc
    id: output_component4
    pin: GPIO25

switch:
  - platform: gpio
    name: $deviceString PUMP OUT 1
    icon: "mdi:pump"
    pin: GPIO13
    id: pump_out_01

binary_sensor:
  - platform: status
    name: $deviceString Status

# Flood sensor still haven't configured, lost it.
# GPIO33 #Flood sensor

# The water sensor is an ultrasonic one, but it uses single pin for trigger and echo
#This is not supported on EspHome
# GPIO32 #Water level sensor
