substitutions:
  deviceString: Hydra

esphome:
  name: hydra

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encription

ota:
  password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.134
    gateway: 192.168.0.1
    subnet: 255.255.255.0

captive_portal:

switch:
  - platform: gpio
    name: $deviceString PUMP OUT 1
    icon: "mdi:pump"
    pin: GPIO13
    id: pump_out_01

  - platform: gpio
    name: $deviceString LED OUT 1
    icon: "mdi:lightbulb_outline"
    pin: GPIO14
    id: led_out_01

  - platform: gpio
    name: $deviceString LED OUT 2
    icon: "mdi:lightbulb_outline"
    pin: GPIO27
    id: led_out_02

  - platform: gpio
    name: $deviceString LED OUT 3
    icon: "mdi:lightbulb_outline"
    pin: GPIO26
    id: led_out_03

  - platform: gpio
    name: $deviceString LED OUT 4
    icon: "mdi:lightbulb_outline"
    pin: GPIO25
    id: led_out_04


binary_sensor:
  - platform: status
    name: $deviceString Status

# Below the GPIO for the sensors, still haven't make them work
# GPIO33 #Flood sensor
# GPIO32 #Water level sensor
